name: Build Luish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build NDS Image
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luish-OS-Build
          path: ./main.nds
